### ISSUE TITLE
Scrolling with mouse gets locked-in

### ISSUE THREAD

**Issue by BurtHarris** [eternagame/EternaJS#226] opened 2020-01-17 03:29 UTC
If you use the mouse on a background area of a puzzle, dragging it implements a scrolling function as long as the mouse button is held down.   This scrolling however misbehaves if the mouse leaves the puzzle region of the screen before the user releases the mouse button.    After that, when the mouse returns to the puzzle, it continues to behave like the user was still holding down the mouse button.

I think the normal solution to this sort of thing is to "capture" the mouse pointer in the mouse-down event, and release capture it on mouse-up.   This seems to map to flashbang's `PointerCapture `class.

**Comment by luxaritas** [comment] 2020-01-17 03:40
I’m assuming that this is because flashbang uses Pixi’s mouse events, which only gets fired when the mouse over the canvas

**Comment by Omei** [comment] 2020-01-17 03:58
I think this behavior (which was introduced when we moved to Pixi from Flash) is the single biggest productivity-sapping regression still remaining. +10 if you can fix it.

**Comment by BurtHarris** [comment] 2020-01-17 05:13
A DOM element's [setPointerCapture()](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) method seems to the key.    Not all browsers support it however, I saw one reference to Safari on mobile as an example, but I'm not sure that's a mainstream browser anymore.   

A search of PIXI's code on github shows _nowhere_ it is mentioned.  Flashbang doesn't seem to call setPointerCapture anywhere either, but it seems like `PointerCapture.beginCapture()` might be the logical place to do so, but we need access to the DOM Element to use.   Where would I find that DOM object?

I'm wondering if @tconkling might be able to comment on this.

**Comment by luxaritas** [comment] 2020-01-17 05:38
If you’re referring to the canvas, Eterna.PIXI_CONTAINER_ID would probably get you close enough. Looks like Safari doesn’t support the API period though: https://caniuse.com/#feat=mdn-api_element_setpointercapture

**Comment by BurtHarris** [comment] 2020-01-17 18:40
Based on the strength of @Omei 's comment, I've found a work-around that doesn't involve setPointerCapture()...   By listening for "pointerout" events during dragging I can make the drag operation stop if the mouse pointer exits the window.   This at least stops the lock-in behavior.   

However, if the mouse pointer re-enters the window, the work-around's effect is that dragging has stopped.  This seems like a small sacrifice to get rid of the lock-in behavior.    I've got this fix on a branch, and will experiment further with it.

**Comment by luxaritas** [comment] 2020-01-17 19:48
What I'd probably do is register a `mouseup` event on `document` itself within PointerCapture (unregistering it as appropriate, of course). This is applicable to things like buttons too - if you release your mouse button outside of the window, you don't then expect hovering over the button to put it in its pressed state. The `document` `mouseup` event even fires when the click is released outside the browser window

**Comment by BurtHarris** [comment] 2020-01-18 00:28
It looks like PIXI supports a special [`pointerupoutside` event](http://pixijs.download/release/docs/PIXI.Container.html#event:pointerupoutside) for this sort of thing.  

The `PointerCapture` class already has support for  `pointerupoutside`.   On the other hand it seems that `DisplayObjectPointerTarget` class and PointerTarget interface do not (yet).   

The `Dragger` class seems based on `DisplayObjectPointerTarget`.    If you can proide any background information comparing these classes, it might help.    Is there a good reason to support the two different approaches?

**Comment by luxaritas** [comment] 2020-01-18 03:40
Right, good catch. DisplayObjectPointerTarget provides a wrapper around Pixi’s mouse events on a DisplayObject, providing a cleaner API. This comes by default with SceneObjects, which create a DOPT for the DisplayObject it manages (and exposes the methods on the object itself, implementing the PointerTarget interface). Dragger creates a DisplayObject and DOPT that handles all mouse events until the mouse up happens. PointerCapture works similarly to Dragger but instead of “handle all mouse input till a mouse up”, it says “handle all mouse input NOT directed at the display object I’m managing, until I’m told I’m no longer needed”.

**Comment by BurtHarris** [comment] 2020-01-20 22:20
Opened pixijs/pixi.js#6346 to inquire about native support in pixi.js

**Comment by luxaritas** [comment] 2020-08-04 01:11
Looks like this has been resolved with Pixi v5

**Closed by luxaritas** 2020-08-04 01:11 UTC
Labels: category: regression, type: bug
