### ISSUE TITLE
Context menu doesn't appear in puzzlemaker

### ISSUE THREAD

**Issue by AlexHalb** [eternagame/EternaJS#460] opened 2020-08-07 16:53 UTC
Bug reported by Xnessax in the chat.

**Comment by guyguy2001** [comment] 2020-12-31 23:14
It seems like the issue is simply that the context menu is not implemented in PuzzleEditMode.
I think that the common button handlers (e.g copy/paste sequence, preferences) should move from PoseEditMode into GameMode, with preferences being overridden in both of them for the EternaViewOptionsMode enum (although maybe there's a better place for it to sit?).
@luxaritas Does this make sense with the responsibility each class holds? If so I'll do it tomorrow

**Comment by luxaritas** [comment] 2020-12-31 23:32
There's a bunch of stuff that isn't implemented in GameMode that should be - and on top of that, there's a bunch of cases of things moved in there that cause problems because GameMode is also used as a base class for DesignBrowserMode when it shouldn't be. Andy and I are working on resolving this in our v2/rearchitecture planning. For now I don't have a strong feeling about whether it would be better to move into GameMode or just reimplement for now. EternaViewOptionsMode is specifically for the options dialog so probably not the best way to go about that...

**Closed** 2021-03-11 03:36 UTC
Labels: type: bug
